module.exports = {
  END: "end of file",
  KEYWORD: "KEYWORD",
  IDENT: "identifier token",
  FLOAT: "float token",
  INT: "int token",
  ELSE: "else",
  IF: "if",
  OR: "or",
  AND: "and",
  NOT: "not",
  PLUS: "+",
  MINUS: "-",
  STAR: "*",
  D_STAR: "**",
  SLASH: "/",
  D_SLASH: "//",
  PERCENT: "%",
  LESS: "<",
  D_LESS: "<<",
  MORE: ">",
  D_MORE: ">>",
  LESS_EQUALS: "<=",
  MORE_EQUALS: ">=",
  IS: "is",
  PIPE: "|",
  CARET: "^",
  AMPERSAND: "&",
  D_EQUALS: "==",
  NOT_EQUALS: "!=",
  IN: "in",
  OR_BRACKET: "(",
  CR_BRACKET: ")",
  SPACE: " ",
  NEWLINE: "new line",
  SEMICOLON: ";",
  COMMA: ",",
  DOT: ".",
  EQUALS: "=",
}
